window:
  padding:
    x: 24
    y: 24
  decorations: transparent
  startup_mode: Maximized

scrolling:
  history: 99999

tabspaces: 2

font:
  normal:
    family: "JetBrains Mono"

  size: 17.0

  use_thin_strokes: true

visual_bell:
  animation: EaseOutExpo
  duration: 150
  color: "0xffffff"

background_opacity: 0.8

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style: Beam

dynamic_title: true
live_config_reload: true

mouse:
  url:
    launcher:
      program: open

key_bindings:
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Add, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
