[package]
  symbol = " "
  disabled = true

[nodejs]
  symbol = " "
  disabled = true

[directory]
  truncation_length = 8

[aws]
  symbol = " "

[battery]
  full_symbol = ""
  charging_symbol = ""
  discharging_symbol = ""

[conda]
  symbol = " "

[git_branch]
  symbol = " "

[golang]
  symbol = " "

[hg_branch]
  symbol = " "

[java]
  symbol = " "

[memory_usage]
  symbol = " "

[php]
  symbol = " "

[python]
  symbol = " "

[ruby]
  symbol = " "

[rust]
  symbol = " "
