shell = "zsh"


# colors
# ----------------------

[plugins.colors]
local = "~/.zsh/modules"
use = ["{{ name }}.plugin.zsh"]


# compinit
# ----------------------

[plugins.async]
github = 'mafredri/zsh-async'

[plugins.compinit]
local = "~/.zsh/modules"
use = ["{{ name }}.plugin.zsh"]


# Completions
# ----------------------

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]


# omz plugins
# ----------------------

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{completion,git,history,key-bindings,directories}.zsh"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{zoxide,aliases,cp,dircycle}/*.plugin.zsh"]


# Other plugins
# ----------------------

[plugins.zoxide]
github = 'ajeetdsouza/zoxide'

[plugins.syntax-highlight]
github = 'marcosmoura/fast-syntax-highlighting'

[plugins.256color]
github = 'chrissicool/zsh-256color'

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.forgit]
github = 'wfxr/forgit'

[plugins.yarn-completion]
github = 'chrisands/zsh-yarn-completions'

[plugins.nx-completion]
github = 'jscutlery/nx-completion'


# Dotfiles
# ----------------------

[plugins.dotfiles]
local = "~/.zsh/modules"
use = ["*.plugin.zsh", "!{colors,compinit}/*.plugin.zsh"]
